# AI recommendations (final proposals at each decision point). kind prop: (player,key,thr,dir,game,src)
P=lambda pl,k,t,d,g,src: dict(kind='prop',player=pl,key=k,thr=t,dir=d,game=g,src=src,label=f"{pl} {('U' if d=='under' else '')}{t if t is not None else ''}{'+' if d=='over' and t is not None else ''} {k}")
S=lambda kind,team,line,g,src,d=None: dict(kind=kind,team=team,line=line,game=g,dir=d,src=src,label=(f"{team} {'ML' if kind=='ml' else ('%+g'%line)}" if kind in('ml','spread') else f"{g} {d.title()} {line}"))
AI=[
# ---- TNF ATL@GB (slot 9 ladder v2 + insured tier 1, slot 10 favorites, dog RR lean, total lean)
P('Jordan Love','completions',19.5,'under','ATL @ GB','TNF T1'),
P('Michael Penix Jr.','completions',19.5,'over','ATL @ GB','TNF T1'),
P("Za'Darius Smith",'sacks',1,'over','ATL @ GB','TNF T1'),
P('Jordan Love','int_thrown',0.5,'under','ATL @ GB','TNF T1 (D1)'),
P('Drake London','rec_yds',69,'over','ATL @ GB','TNF T2'),
P('Drake London','atd',1,'over','ATL @ GB','TNF T2'),
P('Bijan Robinson','rec',5,'over','ATL @ GB','TNF T2'),
P('Bijan Robinson','rush_yds',81,'over','ATL @ GB','TNF T2'),
P('Brian Robinson','rush_yds',24,'over','ATL @ GB','TNF T2'),
P('Michael Penix Jr.','pass_td',1,'over','ATL @ GB','TNF T2 (dropped)'),
P('Matthew Golden','rec_yds',56.5,'over','ATL @ GB','TNF T3'),
P('Christian Watson','rec_yds',72.5,'over','ATL @ GB','TNF T3'),
P('Jordan Love','rush_yds',7.5,'over','ATL @ GB','TNF T3'),
P('Michael Penix Jr.','int_thrown',1,'over','ATL @ GB','TNF T3'),
P('Gervon Dexter','sacks',1,'over','ATL @ GB','TNF T3 (swapped)'),
P('Lukas Van Ness','sacks',1,'over','ATL @ GB','TNF T3'),
P('Matthew Golden','atd',1,'over','ATL @ GB','TNF T3 v1 (D2)'),
P('Bijan Robinson','first_td',None,'over','ATL @ GB','TNF 1st-TD SGP'),
P('Jordan Love','pass_td',2,'over','ATL @ GB','TNF 1st-TD SGP'),
S('ml','ATL',None,'ATL @ GB','TNF lean / dog RR'),
S('total',None,43,'ATL @ GB','TNF lean Under 43','under'),
S('ml','GB',None,'ATL @ GB','Slot 10 favorites (swapped by Andy)'),
S('ml','CIN',None,'CIN @ PIT','Slot 10 favorites'),S('ml','BAL',None,'BAL @ DAL','Slot 10 favorites'),
S('ml','NO',None,'LV @ NO','Slot 10 favorites'),S('ml','JAX',None,'NE @ JAX','Slot 10 favorites'),S('ml','LAR',None,'LAR @ DEN','Slot 10 favorites'),
S('total',None,43.5,'CAR @ CLE','Slot 10 favorites','under'),S('total',None,41.5,'SEA @ WAS','Slot 10 favorites','under'),
# ---- Sunday game card (Codex clean synthesis final + Claude v4/v5 + paper 4-leg + slot 4 T3 + SNF + SuperContest AI five)
S('spread','SF',-8,'ARI @ SF','Clean synthesis #1'),S('spread','CIN',-3,'CIN @ PIT','Clean synthesis #2'),
S('spread','TEN',2,'TEN @ NYG','Clean synthesis #3'),S('total',None,44,'LAR @ DEN','Clean synthesis #4','under'),
S('total',None,42.5,'CAR @ CLE','Clean synthesis #5','under'),S('spread','JAX',-3,'NE @ JAX','Clean synthesis #6'),
S('spread','BAL',-3.5,'BAL @ DAL','Clean synthesis #8 / Slot 4 T3'),S('spread','NYJ',6.5,'NYJ @ DET','Clean synthesis dog RR / SuperContest AI'),
S('spread','TB',1,'MIN @ TB','Clean synthesis dog RR'),
S('spread','LAC',7,'LAC @ BUF','Held / Bills-credit default'),S('spread','IND',2,'HOU @ IND','Held'),S('total',None,40.5,'SEA @ WAS','Held','under'),S('spread','LV',3.5,'LV @ NO','Held'),
S('ml','TEN',None,'TEN @ NYG','Dog-ML RR'),S('ml','NYJ',None,'NYJ @ DET','Dog-ML RR'),S('ml','IND',None,'HOU @ IND','Dog-ML RR'),S('ml','CLE',None,'CAR @ CLE','Dog-ML RR'),S('ml','LV',None,'LV @ NO','Dog-ML RR'),
S('ml','TB',None,'MIN @ TB','Slot 4 T3'),S('total',None,43.5,'LV @ NO','Slot 4 T3','under'),S('spread','SF',-7.5,'ARI @ SF','Paper 4-leg / Slot 4 T3'),
S('total',None,45,'LAR @ DEN','Paper 4-leg','under'),S('total',None,43.5,'CIN @ PIT','Paper 4-leg','under'),
S('spread','DEN',2,'LAR @ DEN','SNF pregame rec'),
S('spread','TEN',2.5,'TEN @ NYG','SuperContest AI five'),S('spread','CIN',-3.5,'CIN @ PIT','SuperContest AI five'),S('spread','SF',-8.5,'ARI @ SF','SuperContest AI five'),
# ---- Sunday props: v2.1 card 7a/7b/7d/7e/8a/8b/single
P('Josh Allen','pass_td',2,'over','LAC @ BUF','7a'),P('Carson Schwesinger','tackles',9,'over','CAR @ CLE','7a'),P('Bhayshul Tuten','rush_yds',53,'over','NE @ JAX','7a'),
P('Patrick Mahomes','pass_td',2,'over','KC @ MIA','7a'),P('Drake Thomas','tackles',7,'over','SEA @ WAS','7a'),P('Jonathan Taylor','rush_yds',72,'over','HOU @ IND','7a'),
P('Brock Purdy','pass_td',2,'over','ARI @ SF','7b'),P('Roquan Smith','tackles',8,'over','BAL @ DAL','7b (off board)'),P('Caleb Downs','tackles',7,'over','BAL @ DAL','7b'),
P('Ashton Jeanty','carries',18,'over','LV @ NO','7b v1'),P('Kirk Cousins','pass_td',2,'over','LV @ NO','7b v5'),P('Bucky Irving','rec',3,'over','MIN @ TB','7b v5'),P('Ashton Jeanty','atd',1,'over','LV @ NO','7b v5'),
P('Parker Washington','rec',5,'over','NE @ JAX','7d'),P('Jacob Rodriguez','tackles',10,'over','KC @ MIA','7d'),P('Nate Wiggins','tackles',4,'over','BAL @ DAL','7d / Stack A v1'),
P('Devon Witherspoon','tackles',5,'over','SEA @ WAS','7d'),P('Breece Hall','carries',14,'over','NYJ @ DET','7d'),P('Derrick Henry','rush_yds',80,'over','BAL @ DAL','7d / Stack A v1'),
P('Blake Corum','rush_yds',38,'over','LAR @ DEN','7d / SNF T1'),P('Kyren Williams','carries',12,'over','LAR @ DEN','7d / Stack B v1'),
P('Josh Allen','atd',1,'over','LAC @ BUF','7e'),P('Derrick Henry','atd',1,'over','BAL @ DAL','7e'),P('Chase Brown','atd',1,'over','CIN @ PIT','7e'),P('Bhayshul Tuten','atd',1,'over','NE @ JAX','7e'),
P('George Kittle','atd',1,'over','ARI @ SF','7e / Stack A v1'),P('Jonathan Taylor','atd',1,'over','HOU @ IND','7e'),P('Kyren Williams','atd',1,'over','LAR @ DEN','7e'),
P('Christian McCaffrey','first_td',None,'over','ARI @ SF','8a'),P('Derrick Henry','first_td',None,'over','BAL @ DAL','8a'),P('Chase Brown','first_td',None,'over','CIN @ PIT','8a'),
P('Kyren Williams','first_td',None,'over','LAR @ DEN','8a re-run'),
P('Josh Allen','tds',2,'over','LAC @ BUF','8b'),P('Derrick Henry','tds',2,'over','BAL @ DAL','8b'),P('Christian McCaffrey','tds',2,'over','ARI @ SF','8b'),
P('Jonathan Taylor','rush_yds',82,'over','HOU @ IND','Optional single'),
# clean synthesis prop candidates + v3 card
P('Joe Burrow','pass_td',2,'over','CIN @ PIT','Clean synthesis / Prop RR'),P('Kyren Williams','rush_yds',54,'over','LAR @ DEN','Clean synthesis'),
P('Rachaad White','rec',3,'over','SEA @ WAS','Clean synthesis'),P('Pat Freiermuth','rec',4,'over','CIN @ PIT','Clean synthesis'),
P('Chase Brown','rush_yds',54,'over','CIN @ PIT','v3 7a'),P('Jadarian Price','rush_yds',42,'over','SEA @ WAS','v3 7a'),P('Lamar Jackson','rush_yds',34,'over','BAL @ DAL','v3 7b'),
P('Christian McCaffrey','atd',1,'over','ARI @ SF','v3 7b'),P('Jaxon Smith-Njigba','atd',1,'over','SEA @ WAS','v3 7e'),P('Jadarian Price','atd',1,'over','SEA @ WAS','v3 7e'),P("Ja'Marr Chase",'atd',1,'over','CIN @ PIT','v3 7e'),
# afternoon stacks
P('Trey McBride','rec',7,'over','ARI @ SF','Stack A'),P('Chris Olave','rec',6,'over','LV @ NO','Stack A'),P('Mark Andrews','rec_yds',39,'over','BAL @ DAL','Stack A v1'),
P('Marlon Humphrey','tackles',4,'over','BAL @ DAL','Stack A final'),P('Derrick Henry','rush_yds',83,'over','BAL @ DAL','Stack A final'),
P('CeeDee Lamb','rec',7,'over','BAL @ DAL','Stack B v1'),P('Chris Olave','rec_yds',77,'over','LV @ NO','Stack B v1'),
P('Devaughn Vele','rec',5,'over','LV @ NO','Stack B v2'),P('Cade Otton','rec',3,'over','MIN @ TB','Stack B v2'),P('Blake Corum','rush_yds',48,'over','LAR @ DEN','Stack B v2'),
P('Justin Jefferson','rec',6,'over','MIN @ TB','Stack B v2'),P('Baker Mayfield','rush_yds',27,'over','MIN @ TB','Stack B v2 opt'),
P('Bo Nix','int_thrown',1,'over','LAR @ DEN','Stack B add'),P('Dak Prescott','pass_td',2,'over','BAL @ DAL','Stack B add'),
P('Tyler Shough','rush_yds',15,'over','LV @ NO','Stack B booster'),P('Juwan Johnson','atd',1,'over','LV @ NO','Stack B booster'),
# SNF v3
P('Kyren Williams','carries',13,'over','LAR @ DEN','SNF T1'),dict(kind='team_total',team='DEN',line=20.5,dir='under',game='LAR @ DEN',src='SNF T1',label='DEN TT U20.5'),
P('Jaylen Waddle','rec',5,'over','LAR @ DEN','SNF T1'),P('Matthew Stafford','int_thrown',1,'over','LAR @ DEN','SNF T2'),P('Terrance Ferguson','rec',5,'over','LAR @ DEN','SNF T2'),
P('Byron Young','sacks',1,'over','LAR @ DEN','SNF T2'),S('total',None,44.5,'LAR @ DEN','SNF T2','under'),
P('Davante Adams','atd',1,'over','LAR @ DEN','SNF T3'),P('Pat Bryant','rec_yds',28,'over','LAR @ DEN','SNF T3'),P('Kobie Turner','sacks',1,'over','LAR @ DEN','SNF T3'),P('Evan Engram','rec_yds',22,'over','LAR @ DEN','SNF T3'),
]
