# Week 4 game recaps. 'experts' = Claude's synthesis of the post-game commentary in
# reports/bets/season-recap/w4expert-commentary.json (sources rendered from that file).
R={
'PIT@CLE':dict(kick='Thu TNF',ai='TNF SGP Under 40 + CLE +3.5; CLE +3.5 led the 10-team parlay. Four BEO prop parlays.',
  happened='Watson led a third straight 4th-quarter comeback; Szmyt hit a 56-yard FG with 10 seconds left. CLE 27–24, total 51.',
  wrong='CLE +3.5 was right, but the Under lost by 11 and sank the SGP. Prop leg instances went 11 of 19; Rodgers U34.5 attempts (threw 40) and Judkins 57+ (53) were among the misses.',
  experts='Credit went to CLE\'s rookie WRs (Boston, Concepcion 9-153) and five sacks; PIT\'s receivers barely separate (~15% of routes), so Rodgers is forced into tight windows.',
  grade='Side ✓ · Under ✗'),
'IND@WSH':dict(kick='Sun 6:30 London',ai='Pass on the side (projection IND by 6, experts 7–4 WSH). IND ML on one BKR parlay.',
  happened='Mariota hurt his MCL in Q1 and 7th-round rookie Kaliakmanis played 3.5 quarters. Taylor 20-95-2. IND 30–13.',
  wrong='IND ML won. Passing on the side was right on the read but cost a cover: IND won by 17.',
  experts='The consensus: the margin flatters IND. Jones had 2 more turnovers, and IND was out-gained by a third-string QB (3.9 vs 5.2 YPP). Buckner was dominant; WSH injuries are the story.',
  grade='IND ML ✓ · pass'),
'ARI@NYG':dict(kick='Sun 10:00',ai='ARI was the card\'s top side: ARI ML (Slots 4, 5, ARI/JAX 2-leg), ARI −2.5 (SC parlay), SuperContest ARI −1.5. Brissett 2+ TD and Winston INT in 7a.',
  happened='ARI led 14–3, then Brissett threw 3 INTs, the last a 98-yard Deonte Banks pick-six from the NYG 4 on the final play. NYG 36–24.',
  wrong='The SuperContest miss and the card\'s worst game: every ARI side lost by 12. Brissett 2+ TD and Winston INT both hit.',
  experts='Both sides\' defenses decided it: NYG\'s goal-line stand plus pick-six; ARI punted three times in the 4th and stalled at the goal line. CBS called it a meltdown for Brissett, his first 3-INT game in 11 years.',
  grade='Side ✗'),
'DAL@HOU':dict(kick='Sun 10:00',ai='HOU over DAL (projection HOU by 4); DAL ML big-money flag set aside. HOU ML on parlays; Montgomery 2+ TD in 8b.',
  happened='HOU led at the half by 10+; DAL scored 28 second-half points. Lamb 17-189-1, Javonte Williams 3 TD, Dak\'s 12-yd TD with 40 seconds left. DAL 34–30.',
  wrong='HOU ML lost outright despite out-gaining DAL 7.6 to 5.5 YPP. Montgomery: 10-24, no TD. Javonte and Lamb ATDs hit.',
  experts='Unanimous: HOU\'s defense collapsed (CB Lassiter allowed 136 yds, the most by a CB this season), not Stroud (347, 2 TD). The big-money DAL flag the card set aside was right.',
  grade='Side ✗'),
'GB@TB':dict(kick='Sun 10:00',ai='Under 38.5 single (Fezzik, Shepardson, Erickson); Jalon Daniels INT in 7a/7d; GB −3 SuperContest alternate.',
  happened='Ugly: GB had penalties on the first play of four drives and turned it over at the TB 1 and 7. Daniels threw 2 INTs in his first start. GB 17–14, total 31.',
  wrong='Best read of the week: the Under won by 7.5, Daniels INT hit, GB ML won. Van Ness sack and C. Watson ATD missed.',
  experts='CBS called it the ugliest win of the week. ESPN noted GB\'s two 4th-quarter turnovers inside the 10 were a first since 2013. Cooper\'s Achilles injury is the lasting cost.',
  grade='Under ✓ · Daniels INT ✓'),
'JAX@CIN':dict(kick='Sun 10:00',ai='JAX ML (+130, big-money flag) in the ARI/JAX 2-leg; JAX +8.5 in the Wong teaser; P. Washington 6+ rec in 7d.',
  happened='JAX took two Burrow INTs, one setting up a TD and one ending a 4th-quarter red-zone drive, through 13 penalties. JAX 22–17.',
  wrong='JAX side was right (won outright). Placed CIN ML/−2.5 lost. Parker Washington caught 1 pass.',
  experts='The JAX formula held: run game plus no turnovers. ESPN: Burrow now has 13 4th-quarter/OT turnovers since 2024. Chase left with a concussion.',
  grade='JAX ✓'),
'LAR@PHI':dict(kick='Sun 10:00',ai='LAR was a counter-consensus pick: LAR ML (Slot 4), LAR −3.5 (SC parlay), SuperContest LAR −3. Stafford 2+ TD and Nacua ATD in 7a.',
  happened='PHI led 20–10; LAR scored 14 unanswered, Kyren\'s TD the go-ahead. PHI went 0-for-12 on 3rd down with 172 yards. LAR 24–20.',
  wrong='LAR ML, LAR −3.5 (by ½) and SuperContest LAR −3 all won. Stafford threw 0 TD, 2 INT, so the 2+ TD leg lost.',
  experts='LAR dominated (415–172 yards) and nearly lost it to penalties and turnovers. PHI\'s offense hit historic lows and lost Barkley, Greenard and Q. Mitchell in-game. Stafford is up to 6 INTs.',
  grade='Side ✓ (−3.5 by ½)'),
'NE@BUF':dict(kick='Sun 10:00',ai='NE +7 (Slot 3 and Hybrid; the Bills-credit default). James Cook 85+ rush in 7d; Cook first TD in 8a.',
  happened='Maye threw 3 TDs, the winner a one-handed Chism catch. NE 29–26 outright.',
  wrong='NE +7 (free bet) won +$8.70. Placed BUF ML and Jay\'s Lock Box Under 48.5 lost. Cook ran for 75 (needed 76) on only 12 carries.',
  experts='Maye\'s first positive-EPA game since last season. BUF\'s secondary was exposed in man (Hairston allowed 2 TD). CBS flagged the under-use of Cook: 12 carries.',
  grade='NE +7 ✓'),
'NYJ@CHI':dict(kick='Sun 10:00',ai='NYJ +3.5 single plus Slot 3 (6 named experts; NYJ passing matchup graded HIGH); Garrett Wilson ATD in 7e.',
  happened='Bagent 268 yards in his first start in 3 years; Monangai 30-146-2. CHI held the ball 42+ minutes. CHI 23–12.',
  wrong='Every NYJ leg lost: 0 for 6. NYJ +3.5 lost by 7.5; the HIGH passing grade produced 157 yards.',
  experts='CHI\'s run game wore NYJ out (CBS: CHI is 10–0 when rushing for 140+). NYJ went 0-for-7 on 3rd down and never forced a punt. ESPN: NYJ has an identity crisis after three straight losses.',
  grade='Side ✗'),
'TEN@BAL':dict(kick='Sun 10:00',ai='SuperContest TEN +11.5 and the SC parlay; Henry 2+ TD (8b) and first TD (8a); Lamar and Pollard ATD.',
  happened='Lamar threw 2 TDs in the first half and left with a high-ankle sprain; BAL didn\'t score again. Loop hit a 64-yard FG. BAL 24–18.',
  wrong='TEN +11.5 covered by 5.5 (SuperContest ✓). TEN +12 won on the 8x4 RR and Lamar ATD lost on the ATD 6-leg; the Henry legs were paper only.',
  experts='Without Lamar, BAL managed 98 yards and no points on 5 drives. TEN\'s Ward-to-Tate (9-145) is real, but Tate fumbled twice. Watch Lamar\'s status for Week 5 (BAL at ATL).',
  grade='TEN ✓'),
'MIA@MIN':dict(kick='Sun 1:05',ai='MIA +9.5 single, Slot 4, Hybrid and the SC parlay; SuperContest MIA +10.5; Willis INT in 7b (a hedge).',
  happened='Reichard kicked 5 FGs; MIN scored no TDs. Gordon 9-100 after Achane\'s injury. MIN 15–10, total 25.',
  wrong='MIA +9.5/+10/+10.5 all covered by 5 and the placed Under 40 won by 15. The Willis INT hedge lost (0 INT).',
  experts='MIN is 4–0 with one offensive TD in 23 possessions over two games. Murray\'s 4.9 air yards per attempt was the lowest by a MIN QB this season; MIA got its first sacks of the year.',
  grade='Side ✓ · Under ✓'),
'DEN@SF':dict(kick='Sun 1:25',ai='The card\'s biggest exposure: DEN +2.5 (Slot 4, SC parlay, SuperContest), DEN ML (Hybrid), DEN +8.5 teaser. 11–2 named experts DEN; CMC 41+ rec yds in 7d.',
  happened='SF\'s defense held DEN to 4.6 YPP; Kittle\'s 56-yd TD sealed it. SF 24–14, still no sacks allowed.',
  wrong='Every DEN side lost, and the teaser died at +8.5 (lost by 10). The 11–2 expert consensus was wrong. CMC had 18 receiving yards. Purdy 2+ TD, Deebo ATD and RJ Harvey 4+ rec hit.',
  experts='Post-game, the consensus flipped: SF can win a defensive game. DEN has scored one first-half TD all season and lost Surtain and Moss. SF is the first team since 2005 with zero sacks allowed through four games.',
  grade='Side ✗'),
'KC@LV':dict(kick='Sun 1:25',ai='LV +4.5 RR leg; Mahomes 2+ TD in 7b; Kelce first TD in 8a; LV +4.5 SuperContest alternate.',
  happened='Walker 22-177-2; Mahomes\' 55-yd shot to Thornton set up the go-ahead score. KC 30–27.',
  wrong='LV +5 covered and KC ML won; the LV ML on the dog RR lost. Mahomes 2+ TD, Walker and Bowers ATDs hit; Kelce and Jeanty ATDs missed.',
  experts='Special teams were the hidden edge: Bassa\'s kickoff punch-out, five Araiza punts inside the 20. Kubiak\'s 4th-down calls were criticized. KC has zero sacks in three weeks.',
  grade='LV +5 ✓'),
'LAC@SEA':dict(kick='Sun 1:25',ai='SEA ML anchor on Slot 3; Darnold 2+ TD in 7b (SEA backfield thin).',
  happened='SEA led 30–13 into the 4th; LAC rallied before Nwosu\'s strip-sack of Herbert. SEA 30–23, a push at −7.',
  wrong='SEA ML and Darnold 2+ TD hit; Emanuel Wilson scored twice. JSN 7+ rec (5) and JSN ATD missed.',
  experts='SEA forced three takeaways; the defense is among the NFL\'s best. LAC is 0–4 at −39 with Alt, McConkey and Slater out; Herbert has a 34.8 rating on deep throws.',
  grade='Side ✓'),
'DET@CAR':dict(kick='Sun SNF',ai='DET ML capped Slots 3 and 4; Gibbs 2+ TD (8b); Jameson Williams ATD (7d, 7e); two SNF island SGPs built around DET.',
  happened='Young went 29/41 for 329 and 2 TD with 11 straight completions to open; McMillan 14-192-2; Hubbard 20-122-2. CAR 32–26.',
  wrong='DET ML lost and sank every BKR parlay it capped. The SNF 8-leg died on Gibbs (4 rec) and Waller (0 TD). Placed CAR ML and Over 50.5 won.',
  experts='DET\'s defense is the problem: seven straight CAR scoring drives, and it is allowing 31.8 PPG (B/R: third-most in 40 years). The Ringer: Young\'s career-high 0.22 EPA/dropback. CAR has 121 points through four weeks, a franchise record.',
  grade='Side ✗'),
'ATL@NO':dict(kick='Mon MNF',ai='Card: ATL +8.5 in the Wong teaser (Tuley, Reynolds). Placed: Kalshi Hooper/Fant/NO D/ST TD combo, three BEO prop SGPs, BKR NO −1 / Over 46.',
  happened='ATL ran for 5 TDs (Bijan 19-145-2, Brian Robinson Jr. 3 TD); Penix 15/20, 223, 1 TD. ATL 45–24, total 69.',
  wrong='All five MNF tickets lost (−$57.81). The Over 46 cashed but NO −1 lost by 22. Fant (abdomen) and Za\'Darius Smith (concussion) had no box line, so both legs were dead; London 5 rec (needed 6). Bijan TD, Blackmon T+A, Penix U30.5 att, Pitts o2.5 rec (3) and Shough 252+/253+ hit.',
  experts='Post-game coverage was about ATL\'s line: two Robinsons, five rushing TDs (matching the franchise record) and no NO answer for the run. NO\'s offense moved the ball (Shough 286) but couldn\'t keep pace.',
  grade='Card ATL ✓ · placed ✗'),
}
