# game recap narratives (written from ESPN box scores + master-intel-narratives-2026-w03.md)
R={
'ATL@GB':dict(kick='Thu TNF',proj='~20–17, low (card brief; no team projection)',ai='Lean ATL (+5 / ML in dog RR) and Under 43. Ladder built on a "trench war": sacks, Love under pressure, few TDs.',
 happened='Atlanta ran 41 times for 242 yards (Bijan 29-194-2) and never allowed a sack. Green Bay ran 9 times for 17 and Love threw 53 passes chasing a 17–7 halftime deficit.',
 wrong='The side read was right; the game-script read was wrong both ways. Pass-rush legs went 0 for 4 (Z. Smith, Wyatt, Van Ness, Dexter all 0 sacks) and the Love completions Under died on volume (28/53). A 35-point Atlanta night pushed the total to 49.',
 grade='Side ✓ · Total ✗'),
'CAR@CLE':dict(kick='Sun 10:00',proj='CLE 20, CAR 17',ai='CLE ML (dog RR) and Under 42.5: field-position game, Browns defense controls early downs.',
 happened='Four Carolina field goals, Watson hit Fannin for the winning TD at 1:48 (plus 2-pt). CLE 21–18, total 39.',
 wrong='The best projection of the week (off by 1 point on the total, 1 on the margin). Misses were player-level: Schwesinger 6 tackles (needed 9) because Carolina threw 48 times instead of running Hubbard 20+; Bryce Young 1 TD.',
 grade='Side ✓ · Total ✓'),
'NYJ@DET':dict(kick='Sun 10:00',proj='DET 26, NYJ 23',ai='NYJ +6.5 / NYJ ML on the HIGH secondary grade (9.79). Projection leaned Over.',
 happened='Geno Smith 31/37, 321, 3 TD confirmed the matchup. NYJ cut it to 24–24 with a 2-pt try at 4:06; Gibbs caught the go-ahead TD at 2:25. DET 31–24, total 55.',
 wrong='NYJ +6.5 lost by half a point. The pass-matchup read held; the price bet on the ML did not. Andy\'s own DET ML and Over 47.5 both won.',
 grade='Side ✗ (by 0.5) · Over ✓'),
'HOU@IND':dict(kick='Sun 10:00',proj='IND 21, HOU 19',ai='IND (six-source consensus): IND ML in dog RR, IND +2 held, Taylor rushing and TD legs.',
 happened='Houston took a 17–16 lead at 1:48; Shrader\'s 53-yard FG with 16 seconds left won it 19–17. Four Shrader field goals; IND 1 of 3 in the red zone.',
 wrong='Side right, props wrong. Taylor finished 23-68 (lines were 72, 73 and 82) and did not score; the Colts stalled inside the 20 and kicked.',
 grade='Side ✓ · Total —'),
'KC@MIA':dict(kick='Sun 10:00',proj='KC 27, MIA 17',ai='Pass on the side (10-point projection vs 10.5). Exposure only through props.',
 happened='Mahomes 20/24, 2 TD; Walker scored the first TD and a receiving TD. KC 24–10.',
 wrong='Nothing broke. Mahomes 2+ TD and the Walker 1st-TD / 2+ TD legs hit. Rodriguez 10+ tackles missed (6): Miami held the ball 34 minutes, so the KC-dominates-snaps case never happened.',
 grade='Pass (KC −10 would have covered)'),
'TEN@NYG':dict(kick='Sun 10:00',proj='TEN 19, NYG 16',ai='Strongest dog of the week: TEN +2 / ML / SuperContest. Winston turnovers decide a low game.',
 happened='Four Giants field goals; Tennessee scored only at 5:35 of the fourth. Winston 14/22, 118, 0 INT. NYG 12–7.',
 wrong='The whole case rested on Winston giving the ball away, and he played clean. The TEN HIGH pass matchup produced 181 yards. The low-total read was right (19 points) but we held no Under.',
 grade='Side ✗ · Total (unplayed) would have ✓'),
'CIN@PIT':dict(kick='Sun 10:00',proj='CIN 23, PIT 17',ai='CIN −3 (No. 2 ranked leg), CIN/PIT Under 43.5 in the paper 4-leg; Burrow/Chase Brown props.',
 happened='Rodgers threw 3 TD passes (first TD on the opening drive), Jaylen Warren ran 17-127, and Boswell kicked the winner at 2:15. PIT 30–27, total 57.',
 wrong='The biggest single leak: CIN and the Under sat on 6 tickets. "PIT backfield uncertain" became a 127-yard Warren day, and the Under missed by 13.5. Burrow 2+ TD and Chase TD still hit.',
 grade='Side ✗ · Total ✗'),
'SEA@WSH':dict(kick='Sun 10:00',proj='SEA 23, WAS 13',ai='Card removed SEA −7.5 on Sunday; held Under 40.5. Favorites parlay had Under 41.5.',
 happened='Mariota threw 3 TDs; Darnold threw for 379 and 4 TDs but also two picks, including Medrano\'s 50-yard pick-six at 3:57. WAS 33–31, total 64.',
 wrong='Worst projection of the week: total off by 28. The flagged counter (WAS pass offense HIGH vs a Seattle secondary missing Love and Okada) is what happened. Seattle ran 18 times for 44, so Jadarian Price legs died. Andy\'s SEA ML and teaser leg lost; JSN 2 TDs and Drake Thomas 9 tackles hit.',
 grade='Side (held) · Total ✗'),
'NE@JAX':dict(kick='Sun 10:00',proj='JAX 24, NE 20',ai='JAX −3 / ML: NE line missing Onwenu, JAX blitz, Tuten and P. Washington underneath.',
 happened='Jacksonville went 5 for 5 in the red zone; Maye threw 2 INTs. JAX 35–6.',
 wrong='Best side of the week. Only P. Washington 5+ receptions missed (3 catches, 1 TD).',
 grade='Side ✓ · Total —'),
'ARI@SF':dict(kick='Sun 1:05',proj='SF 30, ARI 17',ai='No. 1 ranked leg: SF −8 (plus −7/−7.5 variants). Purdy 2+ TD, McCaffrey TD ladder.',
 happened='Purdy 15/27, 297, 4 TD, but Arizona ran 81 plays and held the ball 38:44 (Brissett 38/52). Pineiro missed two PATs. SF 36–30, total 66.',
 wrong='SF covered every number without the two missed extra points (a 38–30 finish covers −7, −7.5 and pushes −8). Arizona\'s volume was the real miss: "Brissett has to chase" meant 52 attempts, not a blowout. Kittle scored twice after we dropped Kittle ATD from 7e and Stack A.',
 grade='Side ✗ (two missed PATs) · Total —'),
'MIN@TB':dict(kick='Sun 1:05',proj='TB 21, MIN 19',ai='TB +1 / TB ML: 0-2 home team trend with seven sources, flagged as one duplicated trend.',
 happened='Myles Price returned a punt 86 yards for a TD; Tampa was sacked 6 times and went 0 for 2 in the red zone. MIN 23–16.',
 wrong='The flagged weakness (one trend counted many times; TB 0-11 ATS) won out. Tampa averaged 3.8 yards per play. Irving 2 catches and Jefferson 2 catches both missed.',
 grade='Side ✗'),
'BAL@DAL':dict(kick='Sun 1:25 (Rio)',proj='BAL 30, DAL 24',ai='BAL −3.5 (conditional on Flowers) / BAL ML; Henry props; Over direction in the projection.',
 happened='Henry 26-89, 2 TD; Loop hit a 56-yard FG at 0:00 after Dallas tied it with 7 seconds left. BAL 34–31, total 65.',
 wrong='The read was right, but the AI\'s −3.5 lost by half a point while Andy\'s BAL ML won. Andrews 24 yards killed every Stack A version, and Dak threw 1 TD. Javonte Williams, not Henry, scored first.',
 grade='Side ✓ (ML) / ✗ (−3.5)'),
'LV@NO':dict(kick='Sun 1:25',proj='NO 22, LV 20',ai='Side skipped; LV ML in the dog RR; Under 43.5/44 in slot 4.',
 happened='Shough threw 42 times for 4 TDs but New Orleans turned it over 4 times. Cousins threw 3 TDs; LV scored the last 19 points. LV 35–27, total 62.',
 wrong='LV ML cashed the dog RR. The Under missed by 18. Jeanty got his carries (19) but no TD; Juwan Johnson scored twice.',
 grade='Dog ML ✓ · Total ✗'),
'LAR@DEN':dict(kick='Sun SNF',proj='LAR 21, DEN 20',ai='Under 44 (No. 4 leg) with a run-first Rams script (Nacua out). Pregame side note: DEN +2.',
 happened='LAR led 16–0 at half. Denver scored 30 after the break: two 2-point conversions, Hufanga\'s 66-yard pick-six, and Nix\'s 1-yard TD at 0:47. DEN 30–26, total 56.',
 wrong='36 leg instances rode on this game and 10 hit. With Nacua out the Rams threw 55 times (Stafford 390 yards) instead of running; Corum had 6 carries for 15. The AI\'s 1st-half Under 22.5 would have won (16), and so would its pregame DEN +2. The live LAR +2 tickets lost.',
 grade='Total ✗ · 1H Under ✓ (unplaced)'),
}
