// src/components/fantasy/FantasyValueBoard.jsx
// F-26 -- Fantasy Value-vs-ADP board (Phase A: history-based projection).
//
// Renders the local report generated by agents/fantasy-value-report.js
// (spec: docs/FANTASY_VALUE_VS_ADP_SPEC.md). Read-only: this tab never
// computes anything itself, it just fetches and displays the last
// generated public/fantasy-value-board.json. Regenerate by running
// `node agents/fantasy-value-report.js --adp <csv> --scoring <ppr|half|standard>`
// and re-syncing (the generator writes the public copy itself).
//
// Kickers/IDP/team-DEF are intentionally not modeled yet (see TASK_BOARD
// F-26b) -- this only covers QB/RB/WR/TE, which is all the generator scores.

import React, { useEffect, useMemo, useState, useCallback } from 'react';
import { Shirt, RefreshCw, Search, TrendingUp, TrendingDown, Minus, HelpCircle, Mic, Star, AlertTriangle } from 'lucide-react';
import { LOCAL_DATA } from '../../lib/apiConfig';
import { getPlayerOverlay } from '../../lib/fantasyOverlayStore';

const POSITION_FILTERS = ['ALL', 'QB', 'RB', 'WR', 'TE'];
const TIER_FILTERS = ['ALL', 'strong_value', 'value', 'fair', 'reach', 'no_projection'];

const SORT_OPTIONS = [
  { value: 'adp', label: 'ADP Rank' },
  { value: 'value_gap', label: 'Value Gap: High → Low' },
  { value: 'proj_pts', label: 'Projected Pts: High → Low' },
];

const TIER_LABEL = {
  strong_value: 'Strong Value',
  value: 'Value',
  fair: 'Fair',
  reach: 'Reach',
  no_projection: 'No Projection',
};

const TIER_STYLE = {
  strong_value: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  value: 'bg-lime-500/20 text-lime-300 border-lime-500/30',
  fair: 'bg-slate-700/40 text-slate-300 border-slate-600/30',
  reach: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
  no_projection: 'bg-slate-800 text-slate-500 border-slate-700',
};

const TIER_ICON = {
  strong_value: TrendingUp,
  value: TrendingUp,
  fair: Minus,
  reach: TrendingDown,
  no_projection: HelpCircle,
};

function fmtPts(v) {
  if (v === null || v === undefined) return '—';
  return Number(v).toFixed(1);
}
function fmtGap(v) {
  if (v === null || v === undefined) return '—';
  return v > 0 ? `+${v}` : `${v}`;
}

function PlayerCard({ row }) {
  const Icon = TIER_ICON[row.tier] || Minus;
  const hasProj = row.tier !== 'no_projection';
  const overlay = getPlayerOverlay(row);

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex items-center gap-4 hover:border-slate-700 transition">
      <div className={`shrink-0 w-11 h-11 rounded-lg flex items-center justify-center border ${TIER_STYLE[row.tier]}`}>
        <Icon size={18} />
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="font-bold text-white truncate">{row.player}</span>
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">{row.position}</span>
          {row.team && <span className="text-[10px] text-slate-600">{row.team}</span>}

          {/* ⭐ Projected Starter Overlay Badge */}
          {overlay?.isProjectedStarter && (
            <span className="inline-flex items-center gap-1 text-[9px] font-bold px-1.5 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/40">
              <Star size={9} className="fill-amber-400 text-amber-400" />
              <span>Starter</span>
            </span>
          )}

          {/* ⚠ Availability Digest Risk Badge */}
          {overlay?.availabilityInfo && (
            <span className="inline-flex items-center gap-1 text-[9px] font-bold px-1.5 py-0.5 rounded bg-rose-500/20 text-rose-300 border border-rose-500/40">
              <AlertTriangle size={9} />
              <span>{overlay.availabilityInfo.event_type.toUpperCase()}</span>
            </span>
          )}
        </div>

        <div className="flex items-center gap-3 mt-1 text-xs text-slate-500 flex-wrap">
          <span>ADP {row.adp}{row.adp_pos_rank ? ` (${row.position}${row.adp_pos_rank})` : ''}</span>
          {hasProj && (
            <span className="text-slate-400 font-medium">
              Proj {fmtPts(row.proj_points)} pts{row.proj_pos_rank ? ` (${row.position}${row.proj_pos_rank})` : ''}
            </span>
          )}
          {row.prior_ppr != null && (
            <span>Prior {fmtPts(row.prior_ppr)} pts / {row.prior_games ?? '—'}g</span>
          )}
        </div>
        {row.label && <div className="text-[11px] text-slate-600 mt-1">{row.label}</div>}
      </div>
      <div className="shrink-0 text-right">
        <span className={`inline-block px-2.5 py-1 rounded-full text-xs font-bold border ${TIER_STYLE[row.tier]}`}>
          {hasProj ? fmtGap(row.value_gap) : 'No Proj'}
        </span>
        <div className="text-[10px] text-slate-600 mt-1 uppercase tracking-wider">{TIER_LABEL[row.tier]}</div>
      </div>
    </div>
  );
}

function StatChip({ label, value, className }) {
  return (
    <div className="bg-slate-900 border border-slate-800 rounded-lg px-3 py-2 min-w-[90px]">
      <div className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">{label}</div>
      <div className={`text-lg font-black ${className || 'text-white'}`}>{value}</div>
    </div>
  );
}

// ─── Podcast Fantasy Intel panel (Phase 3, S302) ─────────────────────────────
// Read-only surface for fantasy_intel-tagged analysis notes from the local
// Gemini/YouTube podcast intel pipeline — the same summary file the
// get_youtube_futures_intel agent tool reads (public/youtube-futures-agent-
// intel-summary.json). No new agent, no new manifest, just a new read path
// into an existing file. See docs/PODCAST_HOLISTIC_INTEL_EXTRACTION_PLAN.md
// Phase 3 step 3.

function PodcastNoteCard({ note }) {
  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
      <div className="flex items-center gap-2 flex-wrap mb-1.5">
        {(note.teams || []).map((t) => (
          <span key={t} className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">{t}</span>
        ))}
        {(note.players || []).length > 0 && (
          <span className="font-bold text-white text-sm">{note.players.join(', ')}</span>
        )}
        <span className="ml-auto flex items-center gap-1 flex-wrap">
          {(note.relevance_tags || []).map((tag) => (
            <span key={tag} className="text-[9px] px-1.5 py-0.5 rounded-full bg-amber-500/10 text-amber-300 border border-amber-500/20 uppercase tracking-wider font-bold">
              {tag.replace(/_/g, ' ')}
            </span>
          ))}
        </span>
      </div>
      {note.topic && <div className="text-sm text-slate-200 font-semibold">{note.topic}</div>}
      {note.summary && <p className="text-xs text-slate-400 mt-1">{note.summary}</p>}
      <div className="flex items-center gap-3 mt-2 text-[11px] text-slate-600 flex-wrap">
        {note.speaker && <span>{note.speaker}</span>}
        {note.confidence && <span className="uppercase tracking-wider">{note.confidence}</span>}
        {note.source?.episode_title && (
          note.source?.timestamp_url
            ? <a href={note.source.timestamp_url} target="_blank" rel="noreferrer" className="text-slate-500 hover:text-amber-300 underline decoration-dotted truncate max-w-[220px]">{note.source.episode_title}</a>
            : <span className="truncate max-w-[220px]">{note.source.episode_title}</span>
        )}
      </div>
      {(note.review_flags || []).length > 0 && (
        <div className="text-[10px] text-rose-400 mt-1.5">Flags: {note.review_flags.join(', ')}</div>
      )}
    </div>
  );
}

function PodcastFantasyIntelPanel() {
  const [state, setState] = useState('loading'); // loading | ready | missing | error
  const [notes, setNotes] = useState([]);
  const [generatedAt, setGeneratedAt] = useState(null);
  const [team, setTeam] = useState('');
  const [player, setPlayer] = useState('');
  const [expanded, setExpanded] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(LOCAL_DATA.YOUTUBE_FUTURES_INTEL);
        if (res.status === 404) { if (!cancelled) setState('missing'); return; }
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const json = await res.json();
        if (cancelled) return;
        const fantasyNotes = (json.notes || []).filter((n) => (n.relevance_tags || []).includes('fantasy_intel'));
        setNotes(fantasyNotes);
        setGeneratedAt(json.generated_at || null);
        setState('ready');
      } catch (e) {
        if (!cancelled) setState('error');
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const filtered = useMemo(() => {
    const teamQ = team.trim().toUpperCase();
    const playerQ = player.trim().toLowerCase();
    return notes.filter((n) => {
      if (teamQ && !(n.teams || []).some((t) => String(t).toUpperCase() === teamQ)) return false;
      if (playerQ && !(n.players || []).some((p) => String(p).toLowerCase().includes(playerQ))) return false;
      return true;
    });
  }, [notes, team, player]);

  // Nothing to show and nothing to explain — stay out of the way rather than
  // adding an empty section to every load of the tab (this data only exists
  // once episodes are re-run against the Phase 1 analysis_notes schema).
  if (state === 'missing' || (state === 'ready' && notes.length === 0)) return null;

  return (
    <div className="bg-slate-900/60 border border-slate-800 rounded-xl overflow-hidden">
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between gap-3 px-4 py-3 text-left"
      >
        <div className="flex items-center gap-2.5">
          <div className="p-1.5 bg-amber-500/10 rounded-lg">
            <Mic size={15} className="text-amber-400" />
          </div>
          <div>
            <div className="text-sm font-bold text-white">Podcast Fantasy Intel</div>
            <p className="text-[11px] text-slate-500">
              {state === 'loading' && 'Loading...'}
              {state === 'error' && 'Failed to load podcast intel'}
              {state === 'ready' && `${filtered.length} of ${notes.length} note${notes.length === 1 ? '' : 's'} · human-reviewed, local-only · not an official pick`}
            </p>
          </div>
        </div>
        <span className="text-slate-500 text-xs">{expanded ? 'Hide' : 'Show'}</span>
      </button>

      {expanded && state === 'ready' && (
        <div className="px-4 pb-4 space-y-3">
          <div className="text-[11px] text-slate-500 bg-slate-950 border border-slate-800 rounded-lg px-3 py-2">
            Role/target-share/breakout-bust commentary pulled from podcast transcripts by the local
            Gemini/YouTube intel pipeline, human-reviewed before promotion. Read-only research
            context — not an official pick, projection input, or production recommendation.
            {generatedAt && ` Generated ${new Date(generatedAt).toLocaleString()}.`}
          </div>
          <div className="flex flex-wrap gap-2.5">
            <input
              value={team}
              onChange={(e) => setTeam(e.target.value)}
              placeholder="Filter team (e.g. KC)"
              className="bg-slate-900 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-slate-600 w-40"
            />
            <input
              value={player}
              onChange={(e) => setPlayer(e.target.value)}
              placeholder="Filter player name"
              className="bg-slate-900 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-slate-600 w-48"
            />
          </div>
          {filtered.length === 0 ? (
            <div className="text-center py-8 text-slate-500 text-xs">No notes match the current filters.</div>
          ) : (
            <div className="space-y-2.5">
              {filtered.map((note) => (
                <PodcastNoteCard key={note.item_id} note={note} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function FantasyValueBoard() {
  const [state, setState] = useState('loading'); // loading | ready | missing | error
  const [data, setData] = useState(null);
  const [errorMsg, setErrorMsg] = useState('');
  const [search, setSearch] = useState('');
  const [positionFilter, setPositionFilter] = useState('ALL');
  const [tierFilter, setTierFilter] = useState('ALL');
  const [sortBy, setSortBy] = useState('adp');
  const [startersOnly, setStartersOnly] = useState(false);

  const load = useCallback(async () => {
    setState('loading');
    try {
      const res = await fetch(LOCAL_DATA.FANTASY_VALUE_BOARD);
      if (res.status === 404) { setState('missing'); return; }
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      setData(json);
      setState('ready');
    } catch (e) {
      setErrorMsg(e.message || 'Failed to load value board');
      setState('error');
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const board = data?.board || [];
  const meta = data?.meta;

  const tierCounts = useMemo(() => {
    const c = { strong_value: 0, value: 0, fair: 0, reach: 0, no_projection: 0 };
    board.forEach((b) => { if (c[b.tier] !== undefined) c[b.tier] += 1; });
    return c;
  }, [board]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    let list = board.filter((b) => {
      if (positionFilter !== 'ALL' && b.position !== positionFilter) return false;
      if (tierFilter !== 'ALL' && b.tier !== tierFilter) return false;
      if (startersOnly) {
        const ov = getPlayerOverlay(b);
        if (!ov?.isProjectedStarter) return false;
      }
      if (q && !b.player?.toLowerCase().includes(q)) return false;
      return true;
    });

    if (sortBy === 'value_gap') {
      list = [...list].sort((a, b) => (b.value_gap ?? -999) - (a.value_gap ?? -999));
    } else if (sortBy === 'proj_pts') {
      list = [...list].sort((a, b) => (b.proj_points ?? -999) - (a.proj_points ?? -999));
    } else {
      list = [...list].sort((a, b) => (a.adp ?? 999) - (b.adp ?? 999));
    }

    return list;
  }, [board, positionFilter, tierFilter, search, startersOnly, sortBy]);

  return (
    <div className="animate-in fade-in zoom-in duration-300 space-y-5 pb-8 max-w-5xl mx-auto">
      {/* Top bar */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-amber-500/10 rounded-lg">
            <Shirt size={20} className="text-amber-400" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-white">Fantasy Value Board</h2>
            <p className="text-xs text-slate-400">
              {meta
                ? `${meta.scoring.toUpperCase()} · prior season ${meta.stats_season} · proj ${meta.proj_games} games · generated ${meta.date}`
                : 'Draft-value projections vs ADP'}
            </p>
          </div>
        </div>
        <button
          onClick={load}
          className="p-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-slate-400 hover:text-white transition-all"
          title="Reload"
        >
          <RefreshCw size={15} className={state === 'loading' ? 'animate-spin' : ''} />
        </button>
      </div>

      {/* Guardrail strip */}
      <div className="text-[11px] text-slate-500 bg-slate-900 border border-slate-800 rounded-lg px-4 py-2.5">
        Phase A — history-based projection (prior-year points/game regressed toward the positional
        mean). Decision support, not advice — pair with injury/situation news. Rookies show as
        "No Projection" since they have no prior-year data. QB/RB/WR/TE only — kickers, IDP, and
        team defense aren't modeled yet (TASK_BOARD F-26b).
      </div>

      <PodcastFantasyIntelPanel />

      {state === 'loading' && (
        <div className="flex items-center justify-center py-20 text-slate-500 gap-3">
          <RefreshCw size={18} className="animate-spin" />
          <span className="text-sm">Loading value board...</span>
        </div>
      )}

      {state === 'missing' && (
        <div className="text-center py-16 bg-slate-900 border border-slate-800 rounded-xl">
          <Shirt size={40} className="mx-auto mb-4 text-slate-700" />
          <p className="text-slate-300 font-bold">No value board generated yet</p>
          <p className="text-slate-500 text-sm mt-2 max-w-md mx-auto">
            Run the report generator, which also syncs the copy this tab reads:
          </p>
          <p className="mt-3 text-xs">
            <code className="bg-slate-950 px-2 py-1 rounded text-slate-300">
              node agents/fantasy-value-report.js --adp data/fantasy/adp-&lt;date&gt;.csv --scoring ppr
            </code>
          </p>
        </div>
      )}

      {state === 'error' && (
        <div className="text-rose-300 bg-rose-500/10 border border-rose-500/30 rounded-lg px-4 py-3 text-sm">
          Failed to load value board: {errorMsg}
        </div>
      )}

      {state === 'ready' && (
        <div className="space-y-5">
          {/* Stats bar */}
          <div className="flex flex-wrap gap-2.5">
            <StatChip label="Strong Value" value={tierCounts.strong_value} className="text-emerald-400" />
            <StatChip label="Value" value={tierCounts.value} className="text-lime-400" />
            <StatChip label="Fair" value={tierCounts.fair} />
            <StatChip label="Reach" value={tierCounts.reach} className="text-rose-400" />
            <StatChip label="No Projection" value={tierCounts.no_projection} className="text-slate-500" />
          </div>

          {/* Controls */}
          <div className="flex flex-wrap items-center justify-between gap-2.5">
            <div className="flex items-center gap-2 flex-wrap flex-1">
              <div className="relative min-w-[180px]">
                <Search size={14} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-500" />
                <input
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  placeholder="Search player..."
                  className="w-full bg-slate-900 border border-slate-800 rounded-lg pl-8 pr-3 py-1.5 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:border-slate-600"
                />
              </div>

              {/* Sort Selector */}
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="bg-slate-900 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-200 outline-none focus:border-slate-600"
              >
                {SORT_OPTIONS.map((s) => (
                  <option key={s.value} value={s.value}>
                    {s.label}
                  </option>
                ))}
              </select>

              {/* Starters Only Toggle */}
              <button
                onClick={() => setStartersOnly((v) => !v)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-xs font-bold transition-all ${
                  startersOnly
                    ? 'bg-amber-500/20 text-amber-300 border-amber-500/40'
                    : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-white'
                }`}
              >
                <Star size={12} className={startersOnly ? 'fill-amber-400 text-amber-400' : ''} />
                <span>Starters Only</span>
              </button>
            </div>

            <div className="flex items-center gap-1 bg-slate-900 border border-slate-800 rounded-lg p-1">
              {POSITION_FILTERS.map((p) => (
                <button
                  key={p}
                  onClick={() => setPositionFilter(p)}
                  className={`px-2.5 py-1 rounded-md text-[11px] font-bold transition-all ${
                    positionFilter === p ? 'bg-amber-500/20 text-amber-300' : 'text-slate-500 hover:text-white'
                  }`}
                >
                  {p}
                </button>
              ))}
            </div>

            <div className="flex items-center gap-1 bg-slate-900 border border-slate-800 rounded-lg p-1 flex-wrap">
              {TIER_FILTERS.map((t) => (
                <button
                  key={t}
                  onClick={() => setTierFilter(t)}
                  className={`px-2.5 py-1 rounded-md text-[11px] font-bold transition-all ${
                    tierFilter === t ? 'bg-amber-500/20 text-amber-300' : 'text-slate-500 hover:text-white'
                  }`}
                >
                  {t === 'ALL' ? 'ALL' : TIER_LABEL[t]}
                </button>
              ))}
            </div>
          </div>

          {/* List */}
          {filtered.length === 0 ? (
            <div className="text-center py-16 text-slate-500 text-sm">No players match the current filters.</div>
          ) : (
            <div className="space-y-2.5">
              {filtered.map((row, i) => (
                <PlayerCard key={`${row.player}-${i}`} row={row} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
